"""empty message

Revision ID: 3a39421360d5
Revises: 6bc21e1579eb
Create Date: 2021-04-05 10:28:49.431936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a39421360d5'
down_revision = '6bc21e1579eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###
