"""empty message

Revision ID: 665fcb5503ad
Revises: 0a2cdb735a4c
Create Date: 2021-04-02 23:36:06.085182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665fcb5503ad'
down_revision = '0a2cdb735a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
